-
  title: Website Design &amp; Development
  description: From business websites to online shops, mobile/web-apps and beyond. Our professional, experienced team are capable and excited to take on your project, whatever the size or style.
  slug: website-design-and-development
  process:
    -
      title: Initial Contact
      description:
        - Whether it’s by phone, email or carrier pigeon we’re always happy to hear about your project.
        - We love to chat about the web as much as we love to work on it. We’re always around for a quick informal chat or an in-depth discussion so feel free to <a href="/work/contact-us" class="bold wdd-page__body">contact us now</a> to get the ball rolling.
    -
      title: Our Suggestions & Your Quote
      description: Once we’ve understood the project we’ll supply you with a quote, along with our suggestions on how your goals can be acheived.
    -
      title: Planning Time
      description:
        - Next up it’s time for a much more in-depth chat. By the end of this meeting, we aim to understand <i>nearly</i> as much as you do about your business; it’s past, present, future and its goals.
        - A big part of this stage is for us to understand the primary focus of your project. If you’re an online shop then sales may be your focus, if you’re a business site, maybe it’s leads you’re looking for.
        - This focus becomes our everything when approach the layout, design and development of your website. Your website needs to do what it’s supposed to do and only by creating a truly bespoke website can this be achieved.
    -
      title: Architecture & Layout
      description:
        - Using all of the knowledge we gained in our planning-meeting it’s time to decide what goes where.
        - This can mean “where does the contact form go?” but can also mean “how do we lay-out the homepage to ensure as many users as possible fill in the contact form?”.
        - By only using our own code that‘s been hand crafted in-house, we have the freedom to design a website that will actually achieve your goals. Something a templated website will always struggle to do.
        - “One-size does not fit all.”
    -
      title: Style
      description:
        - Once we’re happy with the layout, we’ll then concentrate on style. 
        - A unique style can make your website stand out from your competitors. 
        - Already have a visual style? Want to implement the colours or fonts from your logo? No problem. We’re happy to work with existing styles to create a website that is unique, yet fitting to your brand.
    -
      title: Development
      description:
        - Once we have the style in-place, it’s time to get geeky.
        - Your website will be coded from scratch by our in-house team. We strive to stay up to date with the ever-changing internet world. This means using the latest tools and technologies to ensure your website is fast, responsive and compliant with all of the guidelines it should be. 
        - This includes Google. We’ll optimise your site from the ground up to give you a good standing in your SEO, too.
    -
      title: Presentation
      description:
        - It’s time to see your (nearly) finished website!
        - At this stage we’ll send you a private link to your website and ask you for final changes before the website goes live for all the world to see.
    -
      title: Go Live!
      description:
        - When we’re happy and most importantly you’re happy, we’ll work together with your domain provider to push your website live.
        - At this stage we’re happy to discuss any digital marketing requirements you may have to ensure your new website gets the visitors it deserves.
-
  title: Digital Marketing
  description: Need more traffic to your website? Struggling with social media? Not quite hitting the mark on Google? Expandia can help with website traffic, social media success, search engine listings and more.
  slug: digital-marketing
  tools:
    -
      title: SEO
      img: img
      description: | 
        Our approach towards SEO is simple... Get the wesbite in ship-shape and Bristol fashion, then get people talking about the website, all over the internet. Of course there are other areas that need to be covered, but by combining this approach with our bespoke social media system, we've seen great results for all of our SEO clients.
    -
      title: Social Media Marketing
      img: img
      description: | 
        We like to think we're pretty nifty when it comes to social media marketing. Check out pages like <a href="/work/dave-musgrove-blinds" class="bold dm-page-tool__body">this one</a> to see some of our successes. We don't want to give the game away too much but we do have a very unique, hand-crafted strategy on social media and to be frank, it works. We'd love to get you set up on our system and help you achieve the same level of success that our other clients have.
    -
      title: Content Marketing & Blogging
      img: img
      description: | 
        A vital part of any digital marketing strategy is fresh, regular content. We usually suggest that this content is created on your website and shared to social media from there. A blog feels like the most logical place to do this. Need help setting up a blog? Why not <a href="/work/contact-us" class="bold dm-page-tool__body">contact us now</a> to see how we can help you get things set up?
  approach:
    -
      title: A Single Point of Contact
      description: 
        - Here at Expandia we do our best to keep everything under one roof. 
        - Within our monthly packages we can help with, or take complete control of, your; online strategy, social-media, email marketing, blogging, content marketing, website optimisation, and more.
      img: img
    -
      title: A Bespoke Online Strategy
      description:
        - There’s no such thing as a “one size fits all” approach when it comes to digital marketing. Generally speaking though, most businesses are looking for similar results from their website. Whether it’s sales on your online store, leads from your business page or downloads of your content, we can help.
        - In our experience, the success of any digital marketing strategy is - a clear, tangible objective. If your aim is to achieve, for example, more <i>sales</i> then your entire strategy should focus on… you guessed it, <i>sales</i>.
        - We will design you a digital marketing strategy that achieves your objectives by default. Success online is just a formula and formulas can be written.
      img: img
    -
      title: The Proof Is In The Pudding
      description:
        - We also ensure you see the value in your spend by providing an easy to understand, monthly report showing you exactly how your money has been spent and more importantly, the results it has achieved.
        - We’ll email you this report with your monthly invoice so that you can see exactly what you’re paying for. This is our way of showing our transparency and honesty.
      img: img
-
  title: Website Optimisation &amp; Maintenance
  description: If you're getting traffic but struggling with sales or leads, we can help. We're problem solvers at heart and if your website has a problem, we'd love to help you solve it.
  slug: website-optimisation-and-maintenance